#!/usr/bin/env python3
"""Plan and summarize small P17/JN1 parameter sweeps.

This script does not run GPU jobs by default. It writes a shell command file for
the sweep and can summarize completed output directories into one CSV.
"""

from __future__ import annotations

import argparse
import csv
import itertools
import json
import shlex
from pathlib import Path


DEFAULT_SWEEP_ROOT = Path("optimization/vhh/sweeps")


def parse_float_list(raw: str) -> list[float]:
    return [float(x.strip()) for x in raw.split(",") if x.strip()]


def label_float(value: float) -> str:
    return f"{value:g}".replace("-", "m").replace(".", "p")


def env_assignment(key: str, value) -> str:
    return f"{key}={shlex.quote(str(value))}"


def truthy(value) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "y"}


def numeric(value, default=float("nan")) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def make_plan(args) -> int:
    sweep_root = args.sweep_root
    sweep_root.mkdir(parents=True, exist_ok=True)
    args.plan_file.parent.mkdir(parents=True, exist_ok=True)

    commands = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by optimization/vhh/analyze_P17_JN1_sweep.py",
        "# These jobs run sequentially; split this file manually if submitting to a scheduler.",
        "",
    ]

    grid = itertools.product(
        args.start_sigma_fracs,
        args.lambda_max_values,
        args.edit_budget_weights,
        args.weight_esmc_values,
        args.weight_ablang_values,
        args.noise_scales,
        args.seeds,
    )

    count = 0
    for (
        start_sigma_frac,
        lambda_max,
        edit_weight,
        weight_esmc,
        weight_ablang,
        noise_scale,
        seed,
    ) in grid:
        run_name = (
            f"sigma{label_float(start_sigma_frac)}"
            f"_lam{label_float(lambda_max)}"
            f"_editw{label_float(edit_weight)}"
            f"_esm{label_float(weight_esmc)}"
            f"_abl{label_float(weight_ablang)}"
            f"_noise{label_float(noise_scale)}"
            f"_seed{seed}"
        )
        out_dir = sweep_root / run_name
        env = {
            "MODE": "v4",
            "SEED": seed,
            "START_SIGMA_FRAC": start_sigma_frac,
            "NUM_SAMPLING_STEPS": args.num_sampling_steps,
            "STEP_SCALE": args.step_scale,
            "NOISE_SCALE": noise_scale,
            "LAMBDA_MAX": lambda_max,
            "LAMBDA_SCHEDULE": args.lambda_schedule,
            "N_OUTER_ITERATIONS": args.n_outer_iterations,
            "RECYCLING_STEPS": args.recycling_steps,
            "REFOLD_SAMPLING_STEPS": args.refold_sampling_steps,
            "REFOLD_NUM_SAMPLES": args.refold_num_samples,
            "IPSAE_PAE_CUTOFF": args.ipsae_pae_cutoff,
            "REFOLD_RMSD_THRESHOLD": args.refold_rmsd_threshold,
            "BUDGET": args.budget,
            "WEIGHT_EDIT_BUDGET": edit_weight,
            "WEIGHT_ESMC": weight_esmc,
            "WEIGHT_ABLANG": weight_ablang,
            "POLISH_STEPS": args.polish_steps,
            "POLISH_BATCH_SIZE": args.polish_batch_size,
        }
        env_text = " ".join(env_assignment(k, v) for k, v in env.items())
        commands.append(f"echo '== {run_name} =='")
        commands.append(
            f"{env_text} bash optimization/vhh/run_P17_JN1.sh {shlex.quote(str(out_dir))}"
        )
        commands.append("")
        count += 1

    args.plan_file.write_text("\n".join(commands))
    print(f"Wrote {count} commands to {args.plan_file}")
    return count


def load_config(run_dir: Path) -> dict:
    path = run_dir / "config.json"
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return {}


def read_ranked_rows(run_dir: Path) -> list[dict]:
    path = run_dir / "refold_ranked.csv"
    if not path.exists():
        return []
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def summarize(args) -> int:
    rows = []
    for ranked_csv in sorted(args.sweep_root.rglob("refold_ranked.csv")):
        run_dir = ranked_csv.parent
        ranked_rows = read_ranked_rows(run_dir)
        if not ranked_rows:
            continue
        cfg = load_config(run_dir)
        passing = [row for row in ranked_rows if truthy(row.get("rmsd_pass"))]
        ranked = [row for row in passing if str(row.get("rank", "")).strip()]
        best = min(ranked, key=lambda row: int(float(row["rank"]))) if ranked else None
        fallback = max(
            ranked_rows,
            key=lambda row: (
                truthy(row.get("rmsd_pass")),
                numeric(row.get("ipsae_min")),
                numeric(row.get("iptm")),
            ),
        )
        selected = best or fallback
        rows.append(
            {
                "run_dir": str(run_dir),
                "has_passing_rank": best is not None,
                "passing_count": len(passing),
                "candidate_count": len(ranked_rows),
                "rank": selected.get("rank", ""),
                "edit_count": selected.get("edit_count", ""),
                "sample_idx": selected.get("sample_idx", ""),
                "ipsae_min": selected.get("ipsae_min", ""),
                "bt_ipsae": selected.get("bt_ipsae", ""),
                "tb_ipsae": selected.get("tb_ipsae", ""),
                "iptm": selected.get("iptm", ""),
                "geom_interaction_score_refolded": selected.get(
                    "geom_interaction_score_refolded", ""
                ),
                "binder_ca_rmsd_target_aligned": selected.get(
                    "binder_ca_rmsd_target_aligned", ""
                ),
                "rmsd_pass": selected.get("rmsd_pass", ""),
                "start_sigma_frac": cfg.get("start_sigma_frac", ""),
                "noise_scale": cfg.get("noise_scale", ""),
                "step_scale": cfg.get("step_scale", ""),
                "lambda_max": cfg.get("lambda_max", ""),
                "lambda_schedule": cfg.get("lambda_schedule", ""),
                "weight_edit_budget": cfg.get("weight_edit_budget", ""),
                "weight_esmc": cfg.get("weight_esmc", ""),
                "weight_ablang": cfg.get("weight_ablang", ""),
                "budget": cfg.get("edit_budget", ""),
                "ipsae_pae_cutoff": cfg.get("ipsae_pae_cutoff", ""),
                "refold_rmsd_threshold": cfg.get("refold_rmsd_threshold", ""),
                "sequence": selected.get("sequence", ""),
            }
        )

    args.summary_csv.parent.mkdir(parents=True, exist_ok=True)
    if rows:
        with args.summary_csv.open("w", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
            writer.writeheader()
            writer.writerows(rows)
    else:
        args.summary_csv.write_text("")
    print(f"Wrote {len(rows)} summarized runs to {args.summary_csv}")
    return len(rows)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", action="store_true", help="write sweep commands")
    parser.add_argument("--summarize", action="store_true",
                        help="summarize completed sweep outputs")
    parser.add_argument("--sweep-root", type=Path, default=DEFAULT_SWEEP_ROOT)
    parser.add_argument("--plan-file", type=Path,
                        default=Path("optimization/vhh/P17_JN1_sweep_commands.sh"))
    parser.add_argument("--summary-csv", type=Path,
                        default=Path("optimization/vhh/P17_JN1_sweep_summary.csv"))

    parser.add_argument("--start-sigma-fracs", type=parse_float_list,
                        default=parse_float_list("0.2,0.3,0.4,0.5"))
    parser.add_argument("--lambda-max-values", type=parse_float_list,
                        default=parse_float_list("0.5,1.0"))
    parser.add_argument("--edit-budget-weights", type=parse_float_list,
                        default=parse_float_list("10.0,20.0"))
    parser.add_argument("--weight-esmc-values", type=parse_float_list,
                        default=parse_float_list("0.10"))
    parser.add_argument("--weight-ablang-values", type=parse_float_list,
                        default=parse_float_list("0.10"))
    parser.add_argument("--noise-scales", type=parse_float_list,
                        default=parse_float_list("0.88"))
    parser.add_argument("--seeds", type=lambda s: [int(x) for x in s.split(",") if x],
                        default=[0])

    parser.add_argument("--budget", type=int, default=7)
    parser.add_argument("--num-sampling-steps", type=int, default=200)
    parser.add_argument("--step-scale", type=float, default=2.0)
    parser.add_argument("--lambda-schedule", default="sigma_squared",
                        choices=["sigma_squared", "sigma", "constant"])
    parser.add_argument("--n-outer-iterations", type=int, default=3)
    parser.add_argument("--recycling-steps", type=int, default=3)
    parser.add_argument("--refold-sampling-steps", type=int, default=200)
    parser.add_argument("--refold-num-samples", type=int, default=5)
    parser.add_argument("--ipsae-pae-cutoff", type=float, default=12.0)
    parser.add_argument("--refold-rmsd-threshold", type=float, default=2.5)
    parser.add_argument("--polish-steps", type=int, default=200)
    parser.add_argument("--polish-batch-size", type=int, default=16)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    if not args.plan and not args.summarize:
        args.plan = True
        args.summarize = True

    if args.plan:
        make_plan(args)
    if args.summarize:
        summarize(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
